### ISSUE TITLE
Implement function to flat objects by nested keys concatenation with 1st level keys

### ISSUE THREAD

**Issue by georgolden** [metarhia/metautil#113]
Test:
```js
metatests.test('Object: flatFields', (test) => {
  const source = {
    name: { first: 'Andrew', second: 'Johnson' },
    old: true,
    avoid: [1, 2, 3],
    parent: { mother: 'Eva', father: 'Adam' },
  };
  const expected = {
    nameFirst: 'Andrew',
    nameSecond: ' Johnson',
    old: true,
    avoid: [1, 2, 3],
    parentMother: 'Eva',
    parentFather: 'Adam',
  };

  const result = metautil.flatObject(source);

  console.log(result);
  test.strictSame(result, expected);
  test.end();
});

metatests.test('Object: flatFields with key names', (test) => {
  const source = {
    name: { first: 'Andrew', second: 'Johnson' },
    old: true,
    parent: { mother: 'Eva', father: 'Adam' },
  };
  const expected = {
    nameFirst: 'Andrew',
    nameSecond: ' Johnson',
    old: true,
    parent: { mother: 'Eva', father: 'Adam' },
  };

  const result = metautil.flatObject(source, 'name');

  console.log(result);
  test.strictSame(result, expected);
  test.end();
});

```

**Comment by georgolden** [comment]
Write in `lib/utilites.js` your implementation of function `flatObject`

**Comment by dromix** [comment]
What about the case if there is a conflict by property? @georgolden 
`metatests.test('Object: flatFields with same key', (test) => {
  const source = {
    name: { first: 'Andrew', second: 'Johnson' },
    nameFirst: 'Alex',
    old: true,
    parent: { mother: 'Eva', father: 'Adam' },
  };
  const expected = {
    nameFirst: 'Andrew', // or 'Alex' ?
    nameSecond: ' Johnson',
    old: true,
    parent: { mother: 'Eva', father: 'Adam' },
  };

  const result = metautil.flatObject(source, 'name');

  console.log(result);
  test.strictSame(result, expected);
  test.end();
});`

**Comment by georgolden** [comment]
@dromix throw Error

**Comment by AlexBelch** [comment]
I want to do this task

**Comment by tshemsedinov** [comment]
Refs: https://github.com/metarhia/metautil/pull/116
