### ISSUE TITLE
Add tests for parseEvery & nextEvent

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metautil#122]
Now we have tests for:
- parseEvery: https://github.com/metarhia/metautil/blob/a0bc899f7eb1cb0e8360c75ec5e62e35e911bea4/test/utilities.js#L260-L278
- nextEvent: https://github.com/metarhia/metautil/blob/a0bc899f7eb1cb0e8360c75ec5e62e35e911bea4/test/utilities.js#L279-L330

Before optimizing `parseEvery` and `nextEvent` we need more tests.

**Comment by AlexBelch** [comment]
@tshemsedinov 
I want to do this task
but i need to explaine 
what you think about "need more tests"?

Question:
why this test not work
['65s', { YY: -1, MM: -1, DD: -1, wd: -1, hh: -1, mm: 1, ms: 5000 }],
and 65s not divide ti 1 minute and 5s

not ok declarative
    --- wanted                                                    
    +++ found                                                     
    -{"YY":-1,"MM":-1,"DD":-1,"wd":-1,"hh":-1,"mm":1,"ms":5000}   
    +{"YY":-1,"MM":-1,"DD":-1,"wd":-1,"hh":-1,"mm":-1,"ms":65000} 
    message: function metautil.parseEvery("65s")
