### ISSUE TITLE
Implement default values in Collector

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metautil#221]
```js
const default = { userName: 'Marcus', fileName: 'file.txt' };
const ac = collect(['userName', 'fileName'], { default, timeout: 1000 });
```

If values will not be added in 1 sec, default values will be used

**Comment by axbuglak** [comment]
If I understand you correctly, default values must be used after timeout after initialization of collector and not after `set` command
#231

**Comment by axbuglak** [comment]
already done in #231  , but we should also add it to the documentation. After that issue should be closed. And i can also write tests, doc etc. for Futures.

**Comment by tshemsedinov** [comment]
Ok, we need:
- [ ] unittests (node native test runner and asserts)
- [ ] documentation in README.md
- [ ] typings in .d.ts
